describe("cache", function()
	local cache_module

	before_each(function()
		package.loaded["pyworks.core.cache"] = nil
		cache_module = require("pyworks.core.cache")
	end)

	describe("basic operations", function()
		it("should store and retrieve values", function()
			cache_module.set("test_key", "test_value")
			assert.are.equal("test_value", cache_module.get("test_key"))
		end)

		it("should return nil for missing keys", function()
			assert.is_nil(cache_module.get("nonexistent"))
		end)

		it("should invalidate keys", function()
			cache_module.set("test_key", true)
			assert.is_true(cache_module.get("test_key"))
			cache_module.invalidate("test_key")
			assert.is_nil(cache_module.get("test_key"))
		end)
	end)

	describe("custom TTL", function()
		it("should accept optional TTL parameter without error", function()
			assert.has_no.errors(function()
				cache_module.set("test_key", "value", 120)
			end)
			assert.are.equal("value", cache_module.get("test_key"))
		end)
	end)

	describe("invalidation correctness", function()
		it("should invalidate jupytext_installed key", function()
			cache_module.set("jupytext_installed", true)
			assert.is_true(cache_module.get("jupytext_installed"))
			cache_module.invalidate("jupytext_installed")
			assert.is_nil(cache_module.get("jupytext_installed"))
		end)

		it("should invalidate patterns", function()
			cache_module.set("installed_packages_python", { "numpy" })
			cache_module.set("installed_packages_r", { "ggplot2" })
			cache_module.invalidate_pattern("installed_packages_")
			assert.is_nil(cache_module.get("installed_packages_python"))
			assert.is_nil(cache_module.get("installed_packages_r"))
		end)
	end)

	describe("stats", function()
		it("should report correct counts", function()
			cache_module.set("key1", "val1")
			cache_module.set("key2", "val2")
			local stats = cache_module.stats()
			assert.are.equal(2, stats.total)
			assert.are.equal(2, stats.active)
			assert.are.equal(0, stats.expired)
		end)
	end)
end)
